#---------------------------------#
#    environment configuration    #
#---------------------------------#

# Operating system
os:
   - linux
   - osx

language:
   - cpp

compiler:
   - gcc

env:
   matrix:
     - IOS_ANDROID=false
     - IOS_ANDROID=true
   global:
     # Secure strings are specific to a single repository and need to be generated for each user/project
     # ${GH_TOKEN}
     - secure: nZhcYqB9uBZz4NU6u0nB9ofp8XCLfuKzDDuFMfzudpaFyb1lCkDnobMSGI4HLW/EPe1H9pi375PmvAM/pwSy8Dw5DtMdsuPoBhUWgauK9TYLbYnCh4jY8oEdmUOnO1ntF70BdluZL994qmBjgJQlX8/e/J8LGDvGrD/XmaK/TiE=

before_install:

# Scripts to be run before build scripts
install:
   - printf "install"
   - if [[ $TRAVIS_OS_NAME == "linux" && $IOS_ANDROID == false  ]]; then export BUILD_OS=linux; fi
   - if [[ $TRAVIS_OS_NAME == "osx" && $IOS_ANDROID == false ]]; then export BUILD_OS=osx; fi
   - if [[ $TRAVIS_OS_NAME == "linux" && $IOS_ANDROID == true  ]]; then export BUILD_OS=android;fi
   - if [[ $TRAVIS_OS_NAME == "osx" && $IOS_ANDROID == true ]]; then export BUILD_OS=ios; fi
#   - printf "BUILD_OS is set to \"${BUILD_OS}\"\n"
   - chmod a+x ./build-scripts/ci/travis/ci-translator.sh
   - source ./build-scripts/ci/travis/ci-translator.sh
#   - chmod a+x ./build-scripts/ci/travis/tests/travisvartest.sh
#   - ./build-scripts/ci/travis/tests/travisvartest.sh
#   - chmod a+x ./build-scripts/ci/travis/tests/gluevartest.sh
#   - ./build-scripts/ci/travis/tests/gluevartest.sh



#---------------------------------#
#       build configuration       #
#---------------------------------#

before_script:

script:
   # Generic GNU/Linux build
   - bash "${CI_BUILD_DIRECTORY}/build-scripts/${CI_BUILD_OS}.sh"



#---------------------------------#
#     postbuild configuration     #
#---------------------------------#

after_success:
   - chmod a+x "${CI_BUILD_DIRECTORY}/build-scripts/ci/general/update-gh-pages.sh"
   - bash "${CI_BUILD_DIRECTORY}/build-scripts/ci/general/update-gh-pages.sh"

after_failure:

after_script:



#---------------------------------#
#     deployment configuration    #
#---------------------------------#
# The sections "before_deploy" and "after_deploy" are ignored if no deployment is invoked by the "deploy" section. Travis does not currently support custom deploy scripts or explicit deployment enable/disable.

before_deploy:

##deploy:

after_deploy:




