language: cpp
compiler:
  - clang
before_script:
  - '[[ $CXX == "g++" ]] && export CXX=g++-4.7 && export CC=gcc-4.7'
  - sudo apt-get install libpthread-stubs0-dev libgl1-mesa-dev libx11-dev libxrandr-dev libfreetype6-dev libglew1.5-dev libjpeg8-dev libsndfile1-dev libopenal-dev
  - sudo apt-get install libboost-all-dev
  - cmake .
script: 
  - make -j4