os:
  - linux
  - osx
language: 
  - cpp
compiler:
  - gcc
script:
  - if [[ $TRAVIS_OS_NAME == "linux" ]]; then bash build-scripts/linux.sh; fi
  - if [[ $TRAVIS_OS_NAME == "osx" ]]; then bash build-scripts/osx.sh; fi
