os:
  - linux
  - osx
language: 
  - cpp
compiler:
  - gcc
env:
  matrix:
    - IOS_ANDROID=false
    - IOS_ANDROID=true
before_install:
 - sudo apt-get install ia32-libs
 - sudo apt-get install ia32-libs-multiarch
 - sudo apt-get install libc6-i386 lib32stdc++6 lib32gcc1 lib32ncurses5
script:
  # OSX and generic GNU/Linux desktop builds
  #- if [[ $TRAVIS_OS_NAME == "linux" && $IOS_ANDROID == false  ]]; then bash build-scripts/linux.sh; fi
  #- if [[ $TRAVIS_OS_NAME == "osx" && $IOS_ANDROID == false ]]; then bash build-scripts/osx.sh; fi
  
  # iOS and Android builds
  - if [[ $TRAVIS_OS_NAME == "linux" && $IOS_ANDROID == true  ]]; then bash build-scripts/android.sh; fi
  #- if [[ $TRAVIS_OS_NAME == "osx" && $IOS_ANDROID == true ]]; then bash build-scripts/ios.sh; fi

