os:
- linux
- osx
language:
- cpp
compiler:
- gcc
env:
  matrix:
  - BUILD_OS=linux
  - BUILD_OS=osx
  - BUILD_OS=ios
  - BUILD_OS=android
  global:
    secure: CudRipSNP749cyexwhveoLygG7RiqlYdlAnaNJbEivCU9ie91mGcv60W/8woH4M9G52hHoiSgpWX0TXFeV9lnp2lrcRC7+ksJXFVtnHl36vMPyO1qvBp5P+8FK4hSAyk0cu7UjzXYS6iNz+593m3e5a6hfYu4kMyAMZNBJutARM=
matrix:
  exclude:
  - os: osx
  - os: linux
  include:
  - os: linux
    env: BUILD_OS=linux
  - os: linux
    env: BUILD_OS=android
  - os: osx
    env: BUILD_OS=osx
  - os: osx
    env: BUILD_OS=ios
before_install:
install:
- printf "install"
- printf "BUILD_OS set to \"${BUILD_OS}\"\n"
- chmod a+x ./build-scripts/ci/travis/ci-translator.sh
- source ./build-scripts/ci/travis/ci-translator.sh
before_script:
script:
- bash "${CI_BUILD_DIRECTORY}/build-scripts/${CI_BUILD_OS}.sh"

# commenting this out for now
#after_success:
#- chmod a+x "${CI_BUILD_DIRECTORY}/build-scripts/ci/general/update-gh-pages.sh"
#- bash "${CI_BUILD_DIRECTORY}/build-scripts/ci/general/update-gh-pages.sh"
after_failure:
after_script:
before_deploy:
after_deploy:
