# Notes from Appveyor:
#   - Minimal appveyor.yml file is an empty file. All sections are optional.
#   - Indent each level of configuration with 2 spaces. Do not use tabs!
#   - All section names are case-sensitive.
#   - Section names should be unique on each level.

#---------------------------------#
#      general configuration      #
#---------------------------------#

# Version formatting
version: 1.0.{build}

# Black/whitelist
branches:
#Using "only" whitelists branches
   only:
     - master



#---------------------------------#
#    environment configuration    #
#---------------------------------#

# Operating system
os: Windows Server 2012 R2

# Scripts to be run before repository cloning.
init:
   - git config --global core.autocrlf input
   - echo "init_script"

clone_depth: 50

# The clone folder defaults to c:\projects\<APPVEYOR_PROJECT_SLUG>
#clone_folder:

environment:
   GH_TOKEN:
     secure: VzIMNgIGxHkGT1ws7GM1MmX63XyXG2URy+Y9rTWxYq8C5JDJhrhYuazcZXHtPn3f

# Scripts to be run before build scripts
install:
   - ps: Write-Host "install"



#---------------------------------#
#       build configuration       #
#---------------------------------#

build: on

before_build:
   - ps: Write-Host "before_build"

build_script:
   - ps: .\build-scripts\windows.ps1

after_build:
   - ps: Write-Host "after_build"

#---------------------------------#
#        test configuration       #
#---------------------------------#

test: off

before_test:
   - ps: Write-Host "before_test"

test_script:
   - ps: Write-Host "test_script"

after_test:
   - ps: Write-Host "after_test"



#---------------------------------#
#     deployment configuration    #
#---------------------------------#

deploy: off

before_deploy:
   - ps: Write-Host "before_deploy"

deploy_script:
   - ps: Write-Host "deploy_script"

after_deploy:
   - ps: Write-Host "after_deploy"



#---------------------------------#
#        global handlers          #
#---------------------------------#
# If the "on_success" section returns a failure, the "on_failure" section begins automatically.

on_success:
   - ps: sh.exe "${Env:APPVEYOR_BUILD_FOLDER}\build-scripts\ci\appveyor\update-gh-pages.sh"

on_failure:
   - ps: Write-Host "on_failure"

on_finish:
   - ps: Write-Host "on_finish"




