# Notes from Appveyor:
#   - Minimal appveyor.yml file is an empty file. All sections are optional.
#   - Indent each level of configuration with 2 spaces. Do not use tabs!
#   - All section names are case-sensitive.
#   - Section names should be unique on each level.

#---------------------------------#
#      general configuration      #
#---------------------------------#

# Version formatting
version: 1.0.{build}

# Black/whitelist
branches:
#Using "only" whitelists branches
   only:
     - master

#---------------------------------#
#    environment configuration    #
#---------------------------------#

# Operating system
os: Windows Server 2012 R2

# Scripts to be run before repository cloning.
init:
   - git config --global core.autocrlf input
   - echo "init_script"

clone_depth: 50

# The clone folder defaults to c:\projects\<APPVEYOR_PROJECT_SLUG>
#clone_folder:

environment:
   GH_TOKEN:
     secure: VzIMNgIGxHkGT1ws7GM1MmX63XyXG2URy+Y9rTWxYq8C5JDJhrhYuazcZXHtPn3f

# Scripts to be run before build scripts
install: echo "install_script"

#---------------------------------#
#       build configuration       #
#---------------------------------#

# Build scripts
#build_script:
#   - ps: Write-Host "${Env:APPVEYOR_BUILD_FOLDER}"
#   - ps: '.\build-scripts\windows.ps1'

build: on

before_build: echo "before_build"

build_script: echo "build_script"

after_build: echo "after_build"

#---------------------------------#
#        test configuration       #
#---------------------------------#

test: off

before_test: echo "before_test"

test_script: echo "test_script"

after_test: echo "after_test"

#---------------------------------#
#     deployment configuration    #
#---------------------------------#

deploy: off

before_deploy:

deploy_script:

after_deploy:

#---------------------------------#
#        global handlers          #
#---------------------------------#

#on_success:
#   - ps: 'sh.exe "${Env:APPVEYOR_BUILD_FOLDER}\build-scripts\ci\appveyor\update-gh-pages.sh"'

on_success: echo "on_success"

on_failure: echo "on_failure"

on_finish: echo "on_finish"
