# Notes from Appveyor:
#   - Minimal appveyor.yml file is an empty file. All sections are optional.
#   - Indent each level of configuration with 2 spaces. Do not use tabs!
#   - All section names are case-sensitive.
#   - Section names should be unique on each level.

#---------------------------------#
#      general configuration      #
#---------------------------------#

# Version formatting
version: 1.0.{build}

# Black/whitelist
branches:
#Using "only" whitelists branches
   only:
     - master



#---------------------------------#
#    environment configuration    #
#---------------------------------#

# Operating system
os: Windows Server 2012 R2

# Scripts to be run before repository cloning.
init:
   - git config --global core.autocrlf input
   - echo "init_script"

clone_depth: 50

# The clone folder defaults to c:\projects\<APPVEYOR_PROJECT_SLUG>
#clone_folder:

environment:
   GH_TOKEN:
     secure: 2OSJTHsmSnJdJeLSV9TsnetggAGUtT2gcgBlKaM8ertYVhAR34Buz5DzRNDAjuw6

# Scripts to be run before build scripts
install:
   - ps: Write-Host "install"
   - ps: Set-Item -Path "Env:BUILD_OS" -Value "test"
   - ps: New-Item ".\release" -ItemType directory -Force
   - ps: New-Item ".\release\test.txt" -ItemType file -Force
   - ps: .\build-scripts\ci\appveyor\ci-translator.ps1
   - ps: .\build-scripts\ci\appveyor\vartest.ps1
   - ps: sh.exe ".\build-scripts\ci\appveyor\vartest.sh"

#---------------------------------#
#       build configuration       #
#---------------------------------#

build: on

before_build:
   - ps: Write-Host "before_build"

build_script:
   - ps: Write-Host "build_script"

after_build:
   - ps: Write-Host "after_build"

#---------------------------------#
#        test configuration       #
#---------------------------------#

test: off

before_test:
   - ps: Write-Host "before_test"

test_script:
   - ps: Write-Host "test_script"

after_test:
   - ps: Write-Host "after_test"



#---------------------------------#
#     deployment configuration    #
#---------------------------------#

deploy: off

before_deploy:
   - ps: Write-Host "before_deploy"

deploy_script:
   - ps: Write-Host "deploy_script"

after_deploy:
   - ps: Write-Host "after_deploy"



#---------------------------------#
#        global handlers          #
#---------------------------------#
# If the "on_success" section returns a failure, the "on_failure" section begins automatically.

on_success:
   - ps: Write-Host "on_success"
   - ps: Write-Host "Value: true"
   - ps: Set-Item -Path "Env:CI_PULL_REQUEST_BOOLEAN" -Value "true"
   - ps: sh.exe ".\build-scripts\ci\appveyor\gh-pages-test.sh"
   - ps: Write-Host "Value: false"
   - ps: Set-Item -Path "Env:CI_PULL_REQUEST_BOOLEAN" -Value "false"
   - ps: sh.exe ".\build-scripts\ci\appveyor\gh-pages-test.sh"
   - ps: Write-Host "Value: no data"
   - ps: Set-Item -Path "Env:CI_PULL_REQUEST_BOOLEAN" -Value "no data"
   - ps: sh.exe ".\build-scripts\ci\appveyor\gh-pages-test.sh"
   - ps: Write-Host "Value: TRUE"
   - ps: Set-Item -Path "Env:CI_PULL_REQUEST_BOOLEAN" -Value "TRUE"
   - ps: sh.exe ".\build-scripts\ci\appveyor\gh-pages-test.sh"
   - ps: Write-Host "Value: test 1"
   - ps: Set-Item -Path "Env:CI_PULL_REQUEST_BOOLEAN" -Value "test"
   - ps: sh.exe ".\build-scripts\ci\appveyor\gh-pages-test.sh"
   - ps: Write-Host "Value: test 2"
   - ps: Set-Item -Path "Env:CI_PULL_REQUEST_BOOLEAN" -Value "234`nio2testTESTtest230\njsd"
   - ps: sh.exe ".\build-scripts\ci\appveyor\gh-pages-test.sh"
   - ps: Write-Host "Value: null"
   - ps: Set-Item -Path "Env:CI_PULL_REQUEST_BOOLEAN" -Value ""
   - ps: sh.exe ".\build-scripts\ci\appveyor\gh-pages-test.sh"
   - ps: Write-Host "No variable set"
   - ps: Remove-Item -Path "Env:CI_PULL_REQUEST_BOOLEAN"
   - ps: sh.exe ".\build-scripts\ci\appveyor\gh-pages-test.sh"



on_failure:
   - ps: Write-Host "on_failure"

on_finish:
   - ps: Write-Host "on_finish"




