# Notes from Appveyor:
#   - Minimal appveyor.yml file is an empty file. All sections are optional.
#   - Indent each level of configuration with 2 spaces. Do not use tabs!
#   - All section names are case-sensitive.
#   - Section names should be unique on each level.

#---------------------------------#
#      general configuration      #
#---------------------------------#

# Version formatting
version: 1.0.{build}

# Black/whitelist
branches:
#Using "only" whitelists branches
   only:
     - master

#---------------------------------#
#    environment configuration    #
#---------------------------------#

# Operating system
os: Windows Server 2012 R2

# Scripts to be run before repository cloning.
init:
   - git config --global core.autocrlf input

clone_depth: 50

clone_folder: c:\projects\purity2d

hosts:
   queue-server: 127.0.0.1
   db.server.com: 127.0.0.2

environment:
   GH_TOKEN:
     - secure: VzIMNgIGxHkGT1ws7GM1MmX63XyXG2URy+Y9rTWxYq8C5JDJhrhYuazcZXHtPn3f

#install:


#---------------------------------#
#       build configuration       #
#---------------------------------#


build_script:
   - ps: '.\build-scripts\windows.ps1'


#---------------------------------#
#        global handlers          #
#---------------------------------#

on_success:
   - ps: 'sh.exe "${Env:APPVEYOR_BUILD_FOLDER}\build-scripts\ci\appveyor\update-gh-pages.sh"'
